apps/blog/urls.py
from django.urls import path
from .views import single

urlpatterns = [
    path('single/<int:pk>/', single, name='single')
]

apps/main/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]

apps/person/urls.py
from django.urls import path


urlpatterns = [

]

apps/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/blog/models.py
from django.db import models
from person.models import About
from main.models import Category


class Tag(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField(max_length=350)
    image = models.ImageField(upload_to='blogs')
    category = models.ForeignKey(Category, models.CASCADE)
    tags = models.ManyToManyField(Tag)
    content = models.TextField()
    author = models.ForeignKey(About, models.CASCADE)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    blog = models.ForeignKey(Blog, models.CASCADE)
    name = models.CharField(max_length=350)
    email = models.EmailField()
    image = models.ImageField(upload_to='comment', null=True)
    website = models.URLField(null=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

apps/main/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    subject = models.CharField(max_length=250)
    message = models.TextField()

    def __str__(self):
        return self.name


class Carousel(models.Model):
    image = models.ImageField(upload_to='carousel')
    text = models.CharField(max_length=500)

    def __str__(self):
        return self.image.name


class Category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

apps/person/models.py
from django.db import models
from main.models import Category


class About(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='about')
    birthday = models.DateField()
    bio = models.TextField(null=True, blank=True)
    address = models.CharField(max_length=255)
    zip_code = models.IntegerField()
    email = models.EmailField()
    phone = models.CharField(max_length=255)
    projects = models.IntegerField(default=0)
    awards = models.IntegerField(default=0)
    customers = models.IntegerField(default=0)
    cups_of_coffee = models.IntegerField(default=0)
    cv = models.FileField(upload_to='about_cv')

    def __str__(self):
        return self.name


class Resume(models.Model):
    start = models.DateField()
    finish = models.DateField(null=True)
    profession = models.CharField(max_length=250)
    where = models.CharField(max_length=350)
    description = models.TextField()

    def __str__(self):
        return self.profession


class Service(models.Model):
    icon = models.CharField(max_length=250)
    profession = models.CharField(max_length=250)

    def __str__(self):
        return self.profession


class Skill(models.Model):
    profession = models.CharField(max_length=250)
    percent = models.IntegerField()

    def __str__(self):
        return self.profession


class Project(models.Model):
    image = models.ImageField(upload_to='projects')
    category = models.ManyToManyField(Category, blank=True)
    link = models.URLField(null=True, blank=True)
    profession = models.CharField(max_length=250)

    def __str__(self):
        return self.profession

apps/blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ['blog']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

apps/main/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

apps/blog/views.py
from django.shortcuts import render, redirect
from .models import Blog, Category, Tag
from .forms import CommentForm
from django.contrib import messages
from django.contrib.admin import site


def single(request, pk):
    blog = Blog.objects.filter(id=pk).first()
    categories = Category.objects.all()
    blogs = Blog.objects.order_by('-id').all()[:3]
    tags = Tag.objects.all()
    form = CommentForm(request.POST or None, request.FILES)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.blog = blog
        obj.save()
        messages.success(request, f"<strong>Your message successfully sent!!</strong>")
        return redirect('.')
    context = {
        'blog': blog,
        'form': form,
        'categories': categories,
        'blogs': blogs,
        'tags': tags
    }
    return render(request, 'single.html', context)

apps/main/views.py
from django.shortcuts import render, redirect
from .models import Carousel
from person.models import About, Resume, Service, Skill, Project
from blog.models import Blog
from .forms import ContactForm
from django.contrib import messages


def home(request):
    carousel = Carousel.objects.all()
    about = About.objects.last()
    resumes = Resume.objects.all()[:6]
    services = Service.objects.all()
    skills = Skill.objects.all()
    projects = Project.objects.order_by('-id').all()[:6]
    blogs = Blog.objects.order_by('-id').all()
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, f"<strong>Your message successfully sent!!</strong>")
        return redirect('.')
    context = {
        'items': carousel,
        'about': about,
        'resumes': resumes,
        'services': services,
        'skills': skills,
        'projects': projects,
        'blogs': blogs,
        'form': form
    }
    return render(request, 'index.html', context)

apps/person/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Ravshan Giyosov</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script nonce="49030232-2e52-4fed-a456-ccead45be7a4">(function (w, d) {
        !function (eK, eL, eM, eN) {
            eK.zarazData = eK.zarazData || {};
            eK.zarazData.executed = [];
            eK.zaraz = {deferred: [], listeners: []};
            eK.zaraz.q = [];
            eK.zaraz._f = function (eO) {
                return function () {
                    let eP = Array.prototype.slice.call(arguments);
                    eK.zaraz.q.push({m: eO, a: eP})
                }
            };
            for (const eQ of ["track", "set", "debug"]) eK.zaraz[eQ] = eK.zaraz._f(eQ);
            eK.zaraz.init = () => {
                let eR = eL.getElementsByTagName(eN)[0], eS = eL.createElement(eN),
                    eT = eL.getElementsByTagName("title")[0];
                eT && (eK.zarazData.t = eL.getElementsByTagName("title")[0].text);
                eK.zarazData.x = Math.random();
                eK.zarazData.w = eK.screen.width;
                eK.zarazData.h = eK.screen.height;
                eK.zarazData.j = eK.innerHeight;
                eK.zarazData.e = eK.innerWidth;
                eK.zarazData.l = eK.location.href;
                eK.zarazData.r = eL.referrer;
                eK.zarazData.k = eK.screen.colorDepth;
                eK.zarazData.n = eL.characterSet;
                eK.zarazData.o = (new Date).getTimezoneOffset();
                if (eK.dataLayer) for (const eX of Object.entries(Object.entries(dataLayer).reduce(((eY, eZ) => ({...eY[1], ...eZ[1]}))))) zaraz.set(eX[0], eX[1], {scope: "page"});
                eK.zarazData.q = [];
                for (; eK.zaraz.q.length;) {
                    const e_ = eK.zaraz.q.shift();
                    eK.zarazData.q.push(e_)
                }
                eS.defer = !0;
                for (const fa of [localStorage, sessionStorage]) Object.keys(fa || {}).filter((fc => fc.startsWith("_zaraz_"))).forEach((fb => {
                    try {
                        eK.zarazData["z_" + fb.slice(7)] = JSON.parse(fa.getItem(fb))
                    } catch {
                        eK.zarazData["z_" + fb.slice(7)] = fa.getItem(fb)
                    }
                }));
                eS.referrerPolicy = "origin";
                eS.src = "https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(eK.zarazData)));
                eR.parentNode.insertBefore(eS, eR)
            };
            ["complete", "interactive"].includes(eL.readyState) ? zaraz.init() : eK.addEventListener("DOMContentLoaded", zaraz.init)
        }(w, d, 0, "script");
    })(window, document);</script>
</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light site-navbar-target" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="/">Ravshan</a>
        <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse"
                data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav nav ml-auto">
                <li class="nav-item"><a href="/#home-section" class="nav-link"><span>Home</span></a></li>
                <li class="nav-item"><a href="/#about-section" class="nav-link"><span>About</span></a></li>
                <li class="nav-item"><a href="/#resume-section" class="nav-link"><span>Resume</span></a></li>
                <li class="nav-item"><a href="/#services-section" class="nav-link"><span>Services</span></a></li>
                <li class="nav-item"><a href="/#skills-section" class="nav-link"><span>Skills</span></a></li>
                <li class="nav-item"><a href="/#projects-section" class="nav-link"><span>Projects</span></a></li>
                <li class="nav-item"><a href="/#blog-section" class="nav-link"><span>My Blog</span></a></li>
                <li class="nav-item"><a href="/#contact-section" class="nav-link"><span>Contact</span></a></li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}

{% endblock %}

<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">About</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="https://github.com/ravshandev1"><span><i class="fa-brands fa-github"></i></span></a></li>
                        <li class="ftco-animate"><a href="https://t.me/ravshandev1"><span><i class="fa-brands fa-telegram"></i></span></a></li>
                        <li class="ftco-animate"><a href="https://www.linkedin.com/in/ravshan-giyosov-4a9387245/"><span><i class="fa-brands fa-linkedin"></i></span></a></li>
                        <li class="ftco-animate"><a href="https://www.instagram.com/ravshan.giyosov/"><span><i class="fa-brands fa-instagram"></i></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Links</h2>
                    <ul class="list-unstyled">
                        <li><a href="/"><span class="icon-long-arrow-right mr-2"></span>Home</a></li>
                        <li><a href="/#about-section"><span class="icon-long-arrow-right mr-2"></span>About</a></li>
                        <li><a href="/#services-section"><span class="icon-long-arrow-right mr-2"></span>Services</a></li>
                        <li><a href="/#projects-section"><span class="icon-long-arrow-right mr-2"></span>Projects</a></li>
                        <li><a href="/#contact-section"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Services</h2>
                    <ul class="list-unstyled">
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Design</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Development</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Business Strategy</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Data Analysis</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Graphic Design</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">54 A, Mirzo Ulugbek, Tashkent, Uzbekistan</span>
                            </li>
                            <li><a href="tel://998908106763"><span class="icon icon-phone"></span><span
                                    class="text">+998 90 810 67 63</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text"><span
                                    class="__cf_email__" data-cfemail="d7beb9b1b897aeb8a2a5b3b8bab6beb9f9b4b8ba">ravshangiyosov2002@gmail.com</span></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
        </div>
    </div>
</footer>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993"
        integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA=="
        data-cf-beacon='{"rayId":"786e8e1569c70cbf","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2022.11.3","si":100}'
        crossorigin="anonymous"></script>
</body>
</html>

templates/single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
                <div class="col-md-12 ftco-animate pb-5 mb-3 text-center">
                    <h1 class="mb-3 bread">Blog Single Post</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="/">Home <i
                            class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="/#blog-section">Blog <i
                            class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i
                            class="ion-ios-arrow-forward"></i></span></p>
                </div>
            </div>
        </div>
    </section>
    <section class="ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 ftco-animate">
                    <h2 class="mb-3">{{ blog.title }}</h2>
                    <p>{{ blog.content|slice:"150"}}</p>
                    <p>
                        <img src="{{ blog.image.url }}" alt="" class="img-fluid">
                    </p>
                    <p>{{ blog.content|slice:"150:"}}</p>
                    <div class="tag-widget post-tag-container mb-5 mt-5">
                        <div class="tagcloud">
                            {% for i in blog.tags.all %}
                                <a href="#" class="tag-cloud-link">{{ i.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="about-author d-flex p-4 bg-dark">
                        <div class="bio mr-5">
                            <img src="{{ blog.author.image.url }}" style="height: 200px; width: 165px" alt="Image placeholder" class="img-fluid mb-4">
                        </div>
                        <div class="desc">
                            <h3>{{ blog.author.name }}</h3>
                            <p>{{ blog.author.bio|slice:'50' }}</p>
                            <p>{{ blog.author.bio|slice:'50:100' }}</p>
                            <p>{{ blog.author.bio|slice:'100:150' }}</p>
                            <p>{{ blog.author.bio|slice:'150:' }}</p>
                        </div>
                    </div>
                    <div class="pt-5 mt-5">
                        <h3 class="mb-5">{{ blog.comment_set.all.count }} Comments</h3>
                        <ul class="comment-list">
                            {% for i in blog.comment_set.all %}
                                <li class="comment">
                                <div class="vcard bio">
                                    {% if i.image %}
                                    <img src="{{ i.image.url }}" alt="Image placeholder">
                                    {% else %}
                                        <img src="{% static 'images/about.jpg' %}" alt="Image placeholder">
                                    {% endif %}
                                </div>
                                <div class="comment-body">
                                    <h3>{{ i.name }}</h3>
                                    <div class="meta">{{ i.created_at|date:'F d Y'}} at {{ i.created_at|date:"P" }}</div>
                                    <p>{{ i.message }}</p>
{#                                    <p><a href="#" class="reply">Reply</a></p>#}
                                </div>
                            </li>
                            {% endfor %}
                        </ul>

                        <div class="comment-form-wrap pt-5">
                            <h3 class="mb-5">Leave a comment</h3>
                            <form method="post" class="p-5 bg-dark" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="name">Name *</label>
                                    {{ form.name }}
                                </div>
                                <div class="form-group">
                                    <label for="email">Email *</label>
                                    {{ form.email }}
                                </div>
                                <div class="form-group">
                                    <label for="image">Image</label>
                                    {{ form.image }}
                                </div>
                                <div class="form-group">
                                    <label for="website">Website</label>
                                    {{ form.website }}
                                </div>
                                <div class="form-group">
                                    <label for="message">Message</label>
                                    {{ form.message }}
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 sidebar ftco-animate">
{#                    <div class="sidebar-box">#}
{#                        <form action="#" class="search-form">#}
{#                            <div class="form-group">#}
{#                                <span class="icon icon-search"></span>#}
{#                                <input type="text" class="form-control" placeholder="Type a keyword and hit enter">#}
{#                            </div>#}
{#                        </form>#}
{#                    </div>#}
                    <div class="sidebar-box ftco-animate">
                        <h3 class="heading-sidebar">Categories</h3>
                        <ul class="categories">
                            {% for category in categories %}
                                <li><a href="#">{{ category.name }} <span>({{ category.blog_set.all.count }})</span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3 class="heading-sidebar">Recent Blog</h3>
                        {% for i in blogs %}
                            <div class="block-21 mb-4 d-flex">
                            <a class="blog-img mr-4" style="background-image: url({{ i.image.url }});"></a>
                            <div class="text">
                                <h3 class="heading"><a href="#">{{ i.title }}</a></h3>
                                <div class="meta">
                                    <div><a href="#"><span class="icon-calendar"></span> {{ i.created_at|date:'F d Y'}}</a></div>
                                    <div><a href="#"><span class="icon-person"></span> {{ i.author }}</a></div>
                                    <div><a href="#"><span class="icon-chat"></span> {{ i.comment_set.all.count }}</a></div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3 class="heading-sidebar">Tag Cloud</h3>
                        <div class="tagcloud">
                            {% for tag in tags %}
                                <a href="#" class="tag-cloud-link">{{ tag.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
{#                    <div class="sidebar-box ftco-animate">#}
{#                        <h3 class="heading-sidebar">Paragraph</h3>#}
{#                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem#}
{#                            necessitatibus#}
{#                            voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur#}
{#                            similique, inventore eos fugit cupiditate numquam!</p>#}
{#                    </div>#}
                </div>
            </div>
        </div>
    </section>
{% endblock %}